name: 'OC Site Configuration'
description: 'General Configuration and site settings.'
type: module
core: 8.x
version: 8.x-1.0
package: 'Open Citizen'
dependencies:
  - node
  - page_manager
  - panels
  - search
